import fs from 'fs/promises';
import { createBio, getBioById } from '../repositories/bio.repository';
import { prisma } from '../db';
import OpenAI from 'openai';

const openaiApiKey = process.env.OPENAI_API_KEY;
if (!openaiApiKey) throw new Error('Missing OpenAI API key');
const openai = new OpenAI({ apiKey: openaiApiKey });

export async function generateBioFromResume(resumeId: number) {
  // 1. Fetch resume from DB
  console.log(`[BioGen] Fetching resume for resumeId: ${resumeId}`);
  const resume = await prisma.resume.findUnique({ where: { id: resumeId } });
  if (!resume) {
    console.error(`[BioGen] Resume not found for resumeId: ${resumeId}`);
    throw new Error('Resume not found');
  }

  // 2. Load prompt template and inject resume text
  console.log('[BioGen] Loading prompt template...');
  const template = await fs.readFile('src/prompts/bioPrompt.txt', 'utf8');
  const prompt = template.replace('{resumeText}', resume.fileBuffer.toString());
  console.log('[BioGen] Prompt prepared for OpenAI:', prompt.slice(0, 200) + (prompt.length > 200 ? '...' : ''));

  // 3. Call OpenAI API (v6+ syntax)
  console.log('[BioGen] Sending request to OpenAI...');
  let response;
  try {
    response = await openai.chat.completions.create({
      model: 'gpt-3.5-turbo',
      messages: [
        { role: 'system', content: 'You are a professional bio generator.' },
        { role: 'user', content: prompt }
      ],
      temperature: 0.7,
      max_tokens: 500
    });
    console.log('[BioGen] OpenAI response received.');
  } catch (error) {
    console.error('[BioGen] Error during OpenAI API call:', error);
    throw error;
  }
  const bio = response.choices[0]?.message?.content || '';
  console.log('[BioGen] Bio generated by OpenAI:', bio.slice(0, 200) + (bio.length > 200 ? '...' : ''));

  // 4. Store bio in DB
  console.log('[BioGen] Storing generated bio in database...');
  const createdBio = await createBio(resumeId, bio);
  console.log('[BioGen] Bio stored with ID:', createdBio.id);
  return createdBio;
}

export { getBioById };